### ISSUE TITLE
Support for callbacks

### ISSUE THREAD

**Issue by seanlano** [blackketter/Switch#1]
I propose to add a feature to this code, that would add the ability to define a callback method for the Switch class. This callback would be run when the desired state is triggered, eg. when a pushbutton is pressed. 
This would remove the need to run the `poll()` call and then check status with an if statement, making the code in the main loop neater in some cases. 

If I submit a pull request for this, would it be accepted?

**Comment by blackketter** [comment]
That sounds like a great idea.  What API do you propose?

**Comment by seanlano** [comment]
I was thinking something quite simple, just using a pointer. 
In a different project, I've used this to good effect:

In the header:
```C++
void (*__status_callback)(void);
```

And in the CPP: 
```C++
void LEDOutput::setStatusCallback(void (*cb)(void)){
	/// Store the callback function
	__status_callback = cb;
	__status_callback_exists = true;
}
```

Then the callback is called just with `__status_callback()` in the relevant location in `poll()`. 

I suppose I would add some logic in the `poll()` function to check if a callback has been defined and to call it if the conditions are correct. I'd probably also add a `#define` to enable it, so that it won't waste time checking if the user has no intention of using the callback.

**Comment by blackketter** [comment]
Ok, cool.  Some thoughts:

Maybe instead of a #define we create a subclass that has the fields for the callback functions.   

Also, we can do something like:

`if (__status_callback) {
  (__status_callback)();
}`

and not have to have a separate "exists" field.

Finally, would it be useful for the callback to pass a parameter so that a single callback can be used with multiple switches?

**Comment by seanlano** [comment]
OK yeah I agree on the not needing a separate "exists" field - I don't really know why I did that in this other project now, come to think of it. 

And yeah perhaps the callback would be called with a value of "pressed", "released", "long_press", "double_press", "switched_on", "switched_off". 

I'll play around with some things and send a pull request for review.

**Comment by seanlano** [comment]
I'm thinking something like this (pseudo-code in comments): 

```C++
bool Switch::poll()
{ _longPress = _doubleClick = false;
  bool newlevel = digitalRead(pin);

  if(!_longPressLatch)
  { _longPress = on() && ((long)(millis() - pushedTime) > longPressDelay); // true just one time between polls
    _longPressLatch = _longPress; // will be reset at next switch
  }
  // IF longPress() THEN _longPressCallback() 

  if((newlevel != level) & (millis() - _switchedTime >= debounceDelay))
  { _switchedTime = millis();
    level = newlevel;
    _switched = 1;
    _longPressLatch = false;

    if(pushed())
    { _doubleClick = (long)(millis() - pushedTime) < doubleClickDelay;
      pushedTime = millis();
    }
    // IF pushed() THEN _pushedCallback() 
    // ELSE IF released() THEN _releasedCallback() 
    // IF doubleClick() THEN _doubleClickCallback() 
    return _switched;
  }
  return _switched = 0;
}
```

If the switch in use is a toggle switch and not a push button, then the `_pushedCallback()` would be called when the switch is turned on, and `_releasedCallback()` when it is turned off.

**Comment by blackketter** [comment]
Done!
